// Code generated by "stringer -type=Subsystem"; DO NOT EDIT.

package metrics

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RPC-0]
	_ = x[Sensor-1]
	_ = x[Heimdall-2]
	_ = x[System-3]
}

const _Subsystem_name = "RPCSensorHeimdallSystem"

var _Subsystem_index = [...]uint8{0, 3, 9, 17, 23}

func (i Subsystem) String() string {
	if i < 0 || i >= Subsystem(len(_Subsystem_index)-1) {
		return "Subsystem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Subsystem_name[_Subsystem_index[i]:_Subsystem_index[i+1]]
}
